### PR TITLE
Better support for NULLs

### LINKED ISSUE #72: NULL types are mishandled
It seems, due to a quirk in how a protobuf is translated into JSON, the NULL type is left out from the field because it's integer value is `0`: https://github.com/vitessio/vitess/blob/main/proto/query.proto#L111-L112

What happens here is an HTTP response that looks like this for a query such as `select null, 1`.

```
"result": {
    "fields": [
      {
        "name": "null"
      },
      {
        "name": ":vtg1",
        "type": "INT64"
      }
    ],
    "rows": [
      {
        "lengths": [
          "-1",
          "1"
        ],
        "values": "MQ=="
      }
    ]
  }
}
```

The quirk here is that `type` is entirely left off of the fields, resulting in us decoding the row incorrectly.

The equivalent of after decoded by the driver is:

```
{
  headers: [ 'null', ':vtg1' ],
  types: { null: undefined, ':vtg1': 'INT64' },
  fields: [ { name: 'null' }, { name: ':vtg1', type: 'INT64' } ],
  rows: [ { null: null, ':vtg1': '1' } ],
  rowsAffected: null,
  insertId: null,
  size: 1,
  statement: 'select null, 1',
  time: 194
}
```

As we can see, the null column has an undefined type, rather than something such as "NULL" as I'd expect.

Even worse, but albeit an extremely edge case, on a query like `select null`, we actually throw an error:

```
DOMException [InvalidCharacterError]: The string to be decoded is not correctly encoded.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at __node_internal_ (node:internal/util:505:10)
    at atob (node:buffer:1288:11)
    at decodeRow (file:///xxx/node_modules/@planetscale/database/dist/index.js:161:20)
    at parseObjectRow (file:///xxx/node_modules/@planetscale/database/dist/index.js:149:17)
    at file:///xxx/node_modules/@planetscale/database/dist/index.js:158:88
    at Array.map (<anonymous>)
    at parse (file:///xxx/node_modules/@planetscale/database/dist/index.js:158:17)
    at Connection.execute (file:///xxx/node_modules/@planetscale/database/dist/index.js:86:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The HTTP response we get is:

```
  "result": {
    "fields": [
      {
        "name": "null"
      }
    ],
    "rows": [
      {
        "lengths": [
          "-1"
        ]
      }
    ]
  }
```

My assumption here again is a similar quirk, and that `values` is just a missing key entirely since it'd be an empty string representing no data. It's stemming from within atob, so didn't check exactly what's going on, but my assumption is we're passing `undefined` in there, rather than anything else.

My hunch here though is we need to explicitly handle the NULL type better, and can probably fix both issues together.

### PR DESCRIPTION
**Pull request by mattrobenolt**
In general, both bugs fixed here are the result of protojson encoding and fields being omitted from the JSON response:

In the case of a NULL column, the NULL type is omitted from the types enum becasue it's numeric value is "0", and protojson omits this due to it being a default value.

In the case of `select null`, we get another edge case, where the `values` itself is entirely omitted due to it being an empty sequence of bytes. This case is exaggerated for sure, but it is likely to happen if an entire row is simply 1 column of NULL, or even multiple NULLs. So something like, `select foo from table` may yield if too if `foo` is allowed to be NULL.

Fixes #72

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -64,12 +64,12 @@ export interface Config {
...
 interface QueryResultRow {
   lengths: string[]
-  values: string
+  values?: string
 }
 
 export interface Field {
   name: string
-  type: string
+  type?: string
```
Comment (mattrobenolt) [inline src/index.ts:72]: This is the part I'm not super thrilled about, since this type gets exposed publicly and is shared by the internal QueryResult. In practice, the Field that's used by QueryResult would have type optional, but the public Field we spit back out should have it required. I'm not familiar enough with TypeScript to know if there's a way to handle this better. I thought about duplicating the entire Field type as like, `interface RawField` and then keeping `export interface Field` for public, but it'd entirely be copy/pasted except for this one character difference. If there's a better way to handle that, I'd love to hear it.

File: src/index.ts [hunk 2]
```diff
@@ -217,6 +217,15 @@ export class Connection {
...
 
     const fields = result?.fields ?? []
+    // ensure each field has a type assigned,
+    // the only case it would be omitted is in the case of
+    // NULL due to the protojson spec. NULL in our enum
+    // is 0, and empty fields are omitted from the JSON response,
+    // so we should backfill an expected type.
+    fields.forEach((f) => {
+      f.type = f.type || 'NULL'
+    })
```
Comment (dgraham) [inline src/index.ts:227]: The `for…of` loop avoids a function closure and is a little faster.
```suggestion
    for (const field of fields) {
      field.type ||= 'NULL'
    }
```

**Review by dgraham — APPROVED** [review]
Thanks for fixing this! ⚡️

**Review by iheanyi — APPROVED** [review]

File: src/index.ts (hunk 2 above)
Comment (mattrobenolt) [reply src/index.ts]: TIL both `for...of` and `||=`.
